spring:
  datasource:
    url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sddl_soft
mybatis:
  type-aliases-package: com.zy.springboot.domain
  mapper-locations: classpath:mapper/*.xml